### ISSUE TITLE
reply line getting split breaks regex

### ISSUE THREAD

**Issue by acinader** [closeio/quotequail#19]
In the event that the reply line is broken like so:

```
On Thu, Jan 4, 2018 at 11:17 AM, Boo Radley
wrote:
```
When trying to match the regex: ```'^On (.*) wrote:$', # apple mail/gmail reply```

it'll fail cause concatenating will look like this: ```On Thu, Jan 4, 2018 at 11:17 AM, Boo Radleywrote:```

so it wont match.

**Comment by thomasst** [comment]
This should be fixed in https://github.com/closeio/quotequail/pull/21
