### ISSUE TITLE
lxml is required

### ISSUE THREAD

**Issue by charliewolf** [closeio/quotequail#9]
In order to parse html emails, lxml is required. This should be added to setup.py.

**Comment by thomasst** [comment]
It's an optional dependency. If you're just interested in parsing plain text emails, you don't need to install it.

**Comment by charliewolf** [comment]
It should at least be documented. Getting an ImportError when deploying is not the greatest way to find out such things.

**Comment by thomasst** [comment]
Where? The README already says:
> quotequail has no mandatory dependencies, however using HTML methods require libxml.

**Comment by charliewolf** [comment]
Aha, I am stupid and didn't see that.

I still think adding it to setup.py is the right approach, but it's not a particularly strongly held opinion.

**Comment by thomasst** [comment]
I just don't want to make it a mandatory dependency. Also, your tests should have caught it before deploying it.

**Comment by thomasst** [comment]
Feel free to reopen if you have specific suggestions on how to make it clearer, keeping in mind that libxml should stay as an optional dependency
